import Head from 'next/head';
import Banner from '../components/Banner';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner
        title="this is movie title"
        subTitle="this is sub title"
        imgUrl="/static/download.jpg"
      />
    </div>
  );
}
