import Head from 'next/head';
import Banner from '../components/banner/Banner';
import Card from '../components/card/Card';
import SectionCard from '../components/card/SectionCard';
import Navbar from '../components/navbar/Navbar';

export default function Home() {
  return (
    <div className="bg-black">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar userName="daud@gmail.com" />
      <Banner
        title="this is movie title"
        subTitle="this is sub title"
        imgUrl="/static/download.jpg"
      />
      <SectionCard title="Desney" />
    </div>
  );
}
